### ISSUE TITLE
Commercial usage on iOS

### ISSUE THREAD

**Issue by dmsurti** [3drepo/occt#2]
Related to #1, if this library can be built for iOS, is it usable on iOS in a commercial app? IIUC, this is LGPL and would allow commercial usage only with dynamic linking. In that case, I would have to use this as a Cocoa framework on iOS as iOS 8 onwards allows dynamic linking.

Thoughts/feedback greatly appreciated.

**Comment by carmenfan** [comment]
Hi,

This is  a essentially a fork of the official opencascade library(not a real git fork as OCCT is not available on github), which is not owned by us. I would suggest contacting them directly for any legal matters.

https://www.opencascade.com/

**Comment by dmsurti** [comment]
@carmenfan thanks for the quick response. I will connect with the OpenCascade team for clarification.
